---
abstract: 'Client for JSON RPC 2.0 over HTTP'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  Mojolicious::Plugin::JSONRPC2: 0
  Pod::Coverage: 0.18
  Test::CheckManifest: 0.9
  Test::Exception: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.42, CPAN::Meta::Converter version 2.133380'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-JSONRPC2-HTTP
provides:
  MojoX::JSONRPC2::HTTP:
    file: lib/MojoX/JSONRPC2/HTTP.pm
    version: v1.0.1
requires:
  JSON::RPC2: v1.0.0
  JSON::XS: 0
  Mojolicious: 0
  perl: 5.010001
  version: 0.77
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v1.0.1
